const translations = {
    pt: {
        "hero-title": "Paola Gavazzoni",
        "hero-subtitle": "Hardware • Cloud • Engenharia de Software",
        "hero-description": "Líder Técnica Sênior com experiência sólida em Hardware, Software, Arquitetura e Segurança em Nuvem.",
        "link-linkedin": "LinkedIn",
        "link-contact": "Contato",
        "contact-location": "Curitiba, Paraná, Brasil",
        "tab-summary": "Resumo Profissional",
        "tab-projects": "Projetos Pessoais",
        "about-text": "Especialista em transformação digital e otimização de processos, com histórico comprovado de liderança de equipes multidisciplinares e implementação de soluções escaláveis. Atuação em sistemas financeiros críticos e arquitetura cloud-native.",
        "experience-title": "Experiência Profissional",
        "exp1-date": "Outubro de 2024 – Atual",
        "exp1-role": "Squad Leader — Magalu Cloud",
        "exp1-desc": "Liderança técnica em sistemas financeiros críticos e arquitetura cloud-native na primeira cloud pública do Brasil.",
        "exp1-li1": "Arquitetura do sistema de Revenue Assurance",
        "exp1-li2": "Design de integrações enterprise críticas",
        "exp1-li3": "Liderança técnica de squads DevOps",
        "exp1-li4": "Implantação da norma ISO 27001",
        "exp2-date": "Novembro de 2023 – Outubro de 2024",
        "exp2-role": "Líder de Produto e Engenharia — Groner",
        "exp2-desc": "Reescrita e modernização de sistemas legados.",
        "exp2-li1": "QA Automation com Selenium",
        "exp2-li2": "Integração Jira via N8N (100% funcional)",
        "exp2-li3": "Modernização de infra cloud e DevOps",
        "exp2-li4": "Refatoração do produto de CRM",
        "exp3-date": "Abril de 2023 – Novembro de 2023",
        "exp3-role": "Head de Produtos — Klever Tech",
        "exp3-desc": "Startup FinTech focada em análise de crédito e regulamentações financeiras.",
        "exp3-li1": "Liderança da estratégia tecnológica",
        "exp3-li2": "Desenvolvimento de plataforma SaaS regulamentada",
        "exp3-li3": "Gestão de stakeholders e investidores",
        "exp3-li4": "Compliance LGPD e regulamentações BACEN",
        "exp4-date": "Novembro de 2022 – Maio de 2023",
        "exp4-role": "Gerente de Projetos — DoroTech (Claro Pay)",
        "exp4-desc": "Gestão técnica de projeto enterprise crítico para pagamentos.",
        "exp4-li1": "Entrega 100% bem-sucedida do projeto Claro Pay",
        "exp4-li2": "Implementação de práticas DevOps e security by design",
        "exp4-li3": "Documentação técnica e transferência de conhecimento",
        "exp5-date": "Janeiro de 2022 – Junho de 2022",
        "exp5-role": "Product Owner — Kron Digital",
        "exp5-li1": "Product Owner do projeto LDC SHE Digital",
        "exp5-li2": "Gestão de backlog e definição de requisitos",
        "exp5-li3": "Atuação em projetos para o Bradesco",
        "exp6-date": "Agosto de 2021 – Janeiro de 2022",
        "exp6-role": "Product Owner — SóCarrão.com",
        "exp6-li1": "Definição de roadmap e priorização de backlog",
        "exp6-li2": "Análise de métricas e otimização de conversão",
        "exp6-li3": "Gestão de releases",
        "exp7-date": "Abril de 2020 – Abril de 2021",
        "exp7-role": "Assistente de TI — Promefarma",
        "exp7-li1": "Bots para automação de compras licitatórias",
        "exp7-li2": "Automação de processos farmacêuticos",
        "exp7-li3": "Integração com sistema Winner",
        "exp8-date": "Fevereiro de 2018 – Setembro de 2018",
        "exp8-role": "Developer Analyst — PG Mais",
        "exp8-li1": "Desenvolvimento de APIs sistêmicas",
        "exp8-li2": "Automação de processos",
        "exp8-li3": "Integrações FTP e sistemas de URA",
        "education-title": "Formação Acadêmica",
        "edu1": "Pós-graduação em Cibersegurança — PUC Paraná (2025–2027)",
        "edu2": "Pós-graduação Lato Sensu em Tecnologia da Informação — MIT (2022)",
        "edu3": "Bacharelado em Análise e Desenvolvimento de Sistemas — Estácio (2025)",
        "edu4": "Formação em Planejamento e Escalabilidade — G4 Educação (2023)",
        "languages-title": "Idiomas",
        "lang1": "Inglês — Profissional",
        "lang2": "Espanhol — Profissional",
        "projects-title": "Projetos & Publicações",
        "proj1-tags": "Arduino • ESP32 • Robótica",
        "proj1-title": "Robo Nuno",
        "proj1-desc": "Projeto pessoal desenvolvido com Arduino ESP32, Vespa, Servos de 4 canais, sensores ultrassônicos e analógicos. Inclui um joystick virtual desenvolvido em VanillaJS para controle remoto.",
        "proj1-caption": "Robô controlado por ESP32 com sensores e joystick virtual.",
        "proj2-tags": "LinkedIn • Arduino • Tecnologia",
        "proj2-title": "Dispenser de liquidos automatico",
        "proj2-desc": "Sensor de presenca e bomba peristaltica usando biblioteca <a href=\"https://www.arduinolibraries.info/libraries/ultrasonic\" target=\"_blank\" style=\"color: inherit; text-decoration: underline;\">ultrasonic</a> para dispenser de liquidos.",
        "proj2-caption": "Dispenser de líquidos automático com sensor de presença.",
        "proj3-tags": "Projeto Atual • Web Design • IA",
        "proj3-title": "Personal Page",
        "proj3-desc": "Projeto de portifolio pessoal, para expor minhas habilidades com programação web nas stacks HTML, CSS e JavaScript.",
        "proj4-tags": "Phaser • Vue • Game Design",
        "proj4-title": "MusicGuess",
        "proj4-desc": "Jogo de mistério e música onde o objetivo é descriptografar arquivos, identificar pistas no cenário e interpretar código morse para adivinhar a música.",
        "view-github": "Ver repositório no GitHub",
        "coming-soon": "Disponível em breve"
    },
    en: {
        "hero-title": "Paola Gavazzoni",
        "hero-subtitle": "Hardware • Cloud • Software Engineering",
        "hero-description": "Senior Technical Leader with solid experience in Hardware, Software, Architecture, and Cloud Security.",
        "link-linkedin": "LinkedIn",
        "link-contact": "Contact",
        "contact-location": "Curitiba, Parana, Brazil",
        "tab-summary": "Professional Summary",
        "tab-projects": "Personal Projects",
        "about-text": "Specialist in digital transformation and process optimization, with a proven track record of leading multidisciplinary teams and implementing scalable solutions. Experience in critical financial systems and cloud-native architecture.",
        "experience-title": "Professional Experience",
        "exp1-date": "October 2024 – Present",
        "exp1-role": "Squad Leader — Magalu Cloud",
        "exp1-desc": "Technical leadership in critical financial systems and cloud-native architecture at the first public cloud in Brazil.",
        "exp1-li1": "Revenue Assurance system architecture",
        "exp1-li2": "Design of critical enterprise integrations",
        "exp1-li3": "Technical leadership of DevOps squads",
        "exp1-li4": "ISO 27001 standard implementation",
        "exp2-date": "November 2023 – October 2024",
        "exp2-role": "Product and Engineering Leader — Groner",
        "exp2-desc": "Rewriting and modernization of legacy systems.",
        "exp2-li1": "QA Automation with Selenium",
        "exp2-li2": "Jira integration via N8N (100% functional)",
        "exp2-li3": "Cloud infra and DevOps modernization",
        "exp2-li4": "CRM product refactoring",
        "exp3-date": "April 2023 – November 2023",
        "exp3-role": "Head of Products — Klever Tech",
        "exp3-desc": "FinTech startup focused on credit analysis and financial regulations.",
        "exp3-li1": "Technological strategy leadership",
        "exp3-li2": "Development of regulated SaaS platform",
        "exp3-li3": "Stakeholder and investor management",
        "exp3-li4": "LGPD compliance and BACEN regulations",
        "exp4-date": "November 2022 – May 2023",
        "exp4-role": "Project Manager — DoroTech (Claro Pay)",
        "exp4-desc": "Technical management of a critical enterprise project for payments.",
        "exp4-li1": "100% successful delivery of the Claro Pay project",
        "exp4-li2": "Implementation of DevOps practices and security by design",
        "exp4-li3": "Technical documentation and knowledge transfer",
        "exp5-date": "January 2022 – June 2022",
        "exp5-role": "Product Owner — Kron Digital",
        "exp5-li1": "Product Owner for LDC SHE Digital project",
        "exp5-li2": "Backlog management and requirement definition",
        "exp5-li3": "Worked on projects for Bradesco",
        "exp6-date": "August 2021 – January 2022",
        "exp6-role": "Product Owner — SóCarrão.com",
        "exp6-li1": "Roadmap definition and backlog prioritization",
        "exp6-li2": "Metric analysis and conversion optimization",
        "exp6-li3": "Release management",
        "exp7-date": "April 2020 – April 2021",
        "exp7-role": "IT Assistant — Promefarma",
        "exp7-li1": "Bots for bidding purchase automation",
        "exp7-li2": "Automation of pharmaceutical processes",
        "exp7-li3": "Integration with Winner system",
        "exp8-date": "February 2018 – September 2018",
        "exp8-role": "Developer Analyst — PG Mais",
        "exp8-li1": "Systematic API development",
        "exp8-li2": "Process automation",
        "exp8-li3": "FTP integrations and URA systems",
        "education-title": "Education",
        "edu1": "Postgraduate in Cybersecurity — PUC Parana (2025–2027)",
        "edu2": "Postgraduate in Information Technology — MIT (2022)",
        "edu3": "Bachelor in Systems Analysis and Development — Estácio (2025)",
        "edu4": "Planning and Scalability Training — G4 Educação (2023)",
        "languages-title": "Languages",
        "lang1": "English — Professional",
        "lang2": "Spanish — Professional",
        "projects-title": "Projects & Publications",
        "proj1-tags": "Arduino • ESP32 • Robotics",
        "proj1-title": "Robo Nuno",
        "proj1-desc": "Personal project developed with Arduino ESP32, Vespa, 4-channel Servos, ultrasonic and analog sensors. Includes a virtual joystick developed in VanillaJS for remote control.",
        "proj1-caption": "Robot controlled by ESP32 with sensors and virtual joystick.",
        "proj2-tags": "LinkedIn • Arduino • Technology",
        "proj2-title": "Automatic liquid dispenser",
        "proj2-desc": "Presence sensor and peristaltic pump using <a href=\"https://www.arduinolibraries.info/libraries/ultrasonic\" target=\"_blank\" style=\"color: inherit; text-decoration: underline;\">ultrasonic</a> library for liquid dispenser.",
        "proj2-caption": "Automatic liquid dispenser with presence sensor.",
        "proj3-tags": "Current Project • Web Design • IA",
        "proj3-title": "Personal Page",
        "proj3-desc": "Personal portfolio project, to showcase my web programming skills in HTML, CSS and JavaScript stacks.",
        "proj4-tags": "Phaser • Vue • Game Design",
        "proj4-title": "MusicGuess",
        "proj4-desc": "Music mystery game where the goal is to decrypt files, identify clues in the environment, and interpret Morse code to guess the song.",
        "view-github": "View repository on GitHub",
        "coming-soon": "Coming soon"
    },
    es: {
        "hero-title": "Paola Gavazzoni",
        "hero-subtitle": "Hardware • Cloud • Ingeniería de Software",
        "hero-description": "Líder Técnica Senior con sólida experiencia en Hardware, Software, Arquitetura y Seguridad en la Nube.",
        "link-linkedin": "LinkedIn",
        "link-contact": "Contacto",
        "contact-location": "Curitiba, Paraná, Brasil",
        "tab-summary": "Resumen Profesional",
        "tab-projects": "Proyectos Personales",
        "about-text": "Especialista en transformación digital y optimización de procesos, con una trayectoria comprobada liderando equipos multidisciplinarios e implementando soluciones escalables. Experiencia en sistemas financieros críticos y arquitectura cloud-native.",
        "experience-title": "Experiencia Profesional",
        "exp1-date": "Octubre de 2024 – Actual",
        "exp1-role": "Squad Leader — Magalu Cloud",
        "exp1-desc": "Liderazgo técnico en sistemas financieros críticos y arquitectura cloud-native en la primera nube pública de Brasil.",
        "exp1-li1": "Arquitectura del sistema de Revenue Assurance",
        "exp1-li2": "Diseño de integraciones enterprise críticas",
        "exp1-li3": "Liderazgo técnico de squads DevOps",
        "exp1-li4": "Implementación de la norma ISO 27001",
        "exp2-date": "Noviembre de 2023 – Octubre de 2024",
        "exp2-role": "Líder de Producto e Ingeniería — Groner",
        "exp2-desc": "Reescritura y modernización de sistemas legados.",
        "exp2-li1": "Automatización de QA com Selenium",
        "exp2-li2": "Integración Jira vía N8N (100% funcional)",
        "exp2-li3": "Modernización de infraestructura cloud y DevOps",
        "exp2-li4": "Refatoración del producto CRM",
        "exp3-date": "Abril de 2023 – Noviembre de 2023",
        "exp3-role": "Head de Productos — Klever Tech",
        "exp3-desc": "Startup FinTech enfocada en análisis de crédito y regulaciones financieras.",
        "exp3-li1": "Liderazgo de la estrategia tecnológica",
        "exp3-li2": "Desarrollo de plataforma SaaS regulada",
        "exp3-li3": "Gestión de stakeholders e inversores",
        "exp3-li4": "Cumplimiento LGPD y regulaciones BACEN",
        "exp4-date": "Noviembre de 2022 – Mayo de 2023",
        "exp4-role": "Gerente de Proyectos — DoroTech (Claro Pay)",
        "exp4-desc": "Gestión técnica de proyecto enterprise crítico para pagos.",
        "exp4-li1": "Entrega 100% exitosa del proyecto Claro Pay",
        "exp4-li2": "Implementación de prácticas DevOps y security by design",
        "exp4-li3": "Documentación técnica y transferencia de conocimiento",
        "exp5-date": "Enero de 2022 – Junio de 2022",
        "exp5-role": "Product Owner — Kron Digital",
        "exp5-li1": "Product Owner del proyecto LDC SHE Digital",
        "exp5-li2": "Gestión de backlog e definición de requisitos",
        "exp5-li3": "Actuación en proyectos para Bradesco",
        "exp6-date": "Agosto de 2021 – Enero de 2022",
        "exp6-role": "Product Owner — SóCarrão.com",
        "exp6-li1": "Definición de roadmap y priorización de backlog",
        "exp6-li2": "Análisis de métricas y optimización de conversión",
        "exp6-li3": "Gestión de lanzamientos",
        "exp7-date": "Abril de 2020 – Abril de 2021",
        "exp7-role": "Asistente de TI — Promefarma",
        "exp7-li1": "Bots para automatización de compras licitatórias",
        "exp7-li2": "Automatización de procesos farmacéuticos",
        "exp7-li3": "Integración con sistema Winner",
        "exp8-date": "Febrero de 2018 – Septiembre de 2018",
        "exp8-role": "Analista Desarrollador — PG Mais",
        "exp8-li1": "Desarrollo de APIs sistêmicas",
        "exp8-li2": "Automatización de procesos",
        "exp8-li3": "Integraciones FTP y sistemas de URA",
        "education-title": "Formación Académica",
        "edu1": "Postgrado en Ciberseguridad — PUC Paraná (2025–2027)",
        "edu2": "Postgrado en Tecnología de la Información — MIT (2022)",
        "edu3": "Grado en Análisis y Desarrollo de Sistemas — Estácio (2025)",
        "edu4": "Formación en Planificación y Escalabilidad — G4 Educación (2023)",
        "languages-title": "Idiomas",
        "lang1": "Inglés — Profesional",
        "lang2": "Español — Profesional",
        "projects-title": "Proyectos & Publicações",
        "proj1-tags": "Arduino • ESP32 • Robótica",
        "proj1-title": "Robo Nuno",
        "proj1-desc": "Proyecto personal desarrollado con Arduino ESP32, Vespa, Servos de 4 canales, sensores ultrasónicos y analógicos. Inclui um joystick virtual desenvolvido em VanillaJS para controle remoto.",
        "proj1-caption": "Robot controlado por ESP32 com sensores e joystick virtual.",
        "proj2-tags": "LinkedIn • Arduino • Tecnología",
        "proj2-title": "Dispensador de líquidos automático",
        "proj2-desc": "Sensor de presencia y bomba peristáltica usando la librería <a href=\"https://www.arduinolibraries.info/libraries/ultrasonic\" target=\"_blank\" style=\"color: inherit; text-decoration: underline;\">ultrasonic</a> para dispensador de líquidos.",
        "proj2-caption": "Dispensador de líquidos automático con sensor de presencia.",
        "proj3-tags": "Proyecto Atual • Web Design • IA",
        "proj3-title": "Personal Page",
        "proj3-desc": "Proyecto de portafolio personal, para expor mis habilidades con programación web en las stacks HTML, CSS e JavaScript.",
        "proj4-tags": "Phaser • Vue • Game Design",
        "proj4-title": "MusicGuess",
        "proj4-desc": "Juego de misterio y música donde o objetivo es desencriptar arquivos, identificar pistas no cenário e interpretar código morse para adivinhar a música.",
        "view-github": "Ver repositório no GitHub",
        "coming-soon": "Disponible pronto"
    }
};

function changeLanguage(lang) {
    document.documentElement.lang = lang === 'pt' ? 'pt-BR' : lang;
    
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            element.innerHTML = translations[lang][key];
        }
    });

    document.querySelectorAll('.lang-btn').forEach(btn => btn.classList.remove('active'));
    const activeBtn = document.getElementById(`btn-${lang}`);
    if (activeBtn) activeBtn.classList.add('active');

    localStorage.setItem('preferred-lang', lang);
}

function openTab(evt, tabName) {
    const tabcontents = document.getElementsByClassName("tab-content");
    for (let i = 0; i < tabcontents.length; i++) {
        tabcontents[i].classList.remove("active");
    }

    const tablinks = document.getElementsByClassName("tab-button");
    for (let i = 0; i < tablinks.length; i++) {
        tablinks[i].classList.remove("active");
    }

    const targetTab = document.getElementById(tabName);
    if (targetTab) targetTab.classList.add("active");
    if (evt && evt.currentTarget) evt.currentTarget.classList.add("active");
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('preferred-lang') || 'pt';
    changeLanguage(savedLang);
});
